sudo: required
services: 
  - docker

before_install:
  - docker build -t brenda94/docker-react -f Dockerfile.dev .  

script:
  - docker run -e CI=true brenda94/docker-react npm run test -- --coverage